name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # Install Dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Build APK
    - name: Build APK
      run: flutter build apk --release

    # Upload APK Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Flutter-APK
        path: build/app/outputs/flutter-apk/app-release.apk
