name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0' # Flutter এর সঠিক সংস্করণ দিন
        channel: 'stable'         # Channel নিশ্চিত করুন

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Flutter-APK
        path: build/app/outputs/flutter-apk/app-release.apk
